const https = require('https');
const fs = require('fs');
const path = require('path');

const ENDPOINT = 'https://query.wikidata.org/sparql';
const USER_AGENT = 'HistoryFlow/1.0 (history atlas project; benny.baum@gmail.com)';
const DELAY_MS = 4000;

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function fetchJson(sparql) {
  const url = `${ENDPOINT}?format=json&query=${encodeURIComponent(sparql)}`;
  return new Promise((resolve, reject) => {
    const req = https.get(url, {
      headers: {
        'User-Agent': USER_AGENT,
        'Accept': 'application/sparql-results+json',
      },
    }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode}: ${data.slice(0, 300)}`));
          return;
        }
        try { resolve(JSON.parse(data)); }
        catch (e) { reject(new Error(`JSON parse: ${e.message}`)); }
      });
    });
    req.on('error', reject);
    req.setTimeout(90000, () => req.destroy(new Error('Timeout')));
  });
}

function parseCoord(s) {
  if (!s) return null;
  const m = s.match(/Point\(([+-]?\d+\.?\d*)\s+([+-]?\d+\.?\d*)\)/);
  return m ? [parseFloat(m[1]), parseFloat(m[2])] : null;
}

function parseYear(s) {
  if (!s) return null;
  const m = s.match(/^(-?\d+)-/);
  return m ? parseInt(m[1], 10) : null;
}

function importance(sitelinks) {
  const n = parseInt(sitelinks, 10) || 0;
  if (n >= 50) return 5;
  if (n >= 20) return 4;
  if (n >= 8)  return 3;
  if (n >= 3)  return 2;
  return 1;
}

function makeQuery(typeValues, requireInception = false) {
  const typeFilter = Array.isArray(typeValues)
    ? `VALUES ?type { ${typeValues.map(v => `wd:${v}`).join(' ')} }\n  ?city wdt:P31 ?type .`
    : `?city wdt:P31 wd:${typeValues} .`;
  const inceptionLine = requireInception
    ? '?city wdt:P571 ?inception .'
    : 'OPTIONAL { ?city wdt:P571 ?inception }';
  return `
SELECT DISTINCT ?city ?cityLabel ?coord ?inception ?countryLabel ?sitelinks WHERE {
  ${typeFilter}
  ?city wdt:P625 ?coord .
  ${inceptionLine}
  OPTIONAL { ?city wdt:P17 ?country }
  OPTIONAL { ?city wikibase:sitelinks ?sitelinks }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
} LIMIT 10000`;
}

const QUERIES = [
  { name: 'ancient_cities',       sparql: makeQuery('Q15661340') },
  { name: 'roman_byzantine_etc',  sparql: makeQuery(['Q2202509','Q81830252','Q69391739','Q192601','Q3920245','Q142085','Q5228121','Q100268926','Q5500203']) },
  { name: 'polis',                sparql: makeQuery('Q148837') },
  { name: 'tell',                 sparql: makeQuery('Q755017') },
  { name: 'archaeological_sites', sparql: makeQuery('Q839954', true) },
  { name: 'cities_with_dates',    sparql: makeQuery('Q515', true) },
];

async function main() {
  const seen = new Set();
  const cities = [];

  for (const q of QUERIES) {
    process.stdout.write(`Fetching ${q.name}... `);
    try {
      const json = await fetchJson(q.sparql);
      const rows = json.results.bindings;
      let added = 0;

      for (const row of rows) {
        const qid = row.city?.value?.split('/').pop();
        if (!qid || seen.has(qid)) continue;
        seen.add(qid);

        const coord = parseCoord(row.coord?.value);
        if (!coord) continue;

        const name = row.cityLabel?.value || '';
        if (!name || /^Q\d+$/.test(name)) continue; // skip unlabeled

        const country = row.countryLabel?.value || '';
        const year    = parseYear(row.inception?.value);
        const imp     = importance(row.sitelinks?.value);

        cities.push([name, country, coord[0], coord[1], year, imp]);
        added++;
      }
      console.log(`${rows.length} rows → ${added} new (total: ${cities.length})`);
    } catch (e) {
      console.log(`ERROR: ${e.message}`);
    }
    await sleep(DELAY_MS);
  }

  // Sort by founding year (nulls last), then name
  cities.sort((a, b) => {
    const ya = a[4] ?? Infinity, yb = b[4] ?? Infinity;
    return ya !== yb ? ya - yb : a[0].localeCompare(b[0]);
  });

  const lines = cities.map(([name, country, lon, lat, year, imp]) =>
    `  [${JSON.stringify(name)}, ${JSON.stringify(country)}, ${lon.toFixed(3)}, ${lat.toFixed(3)}, ${year ?? 'null'}, ${imp}]`
  );

  const output = `// Auto-generated by scripts/fetch_cities.js — ${new Date().toISOString().slice(0,10)}
// ${cities.length} cities from Wikidata
window.CITIES_DATA = [\n${lines.join(',\n')}\n];\n`;

  const outPath = path.join(__dirname, '..', 'project', 'data', 'cities_wikidata.js');
  fs.writeFileSync(outPath, output, 'utf8');
  console.log(`\nDone. Written to ${outPath}`);
}

main().catch(e => { console.error(e); process.exit(1); });
