const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, '..', 'project', 'data');
const srcPath  = path.join(dataDir, 'cities_wikidata.js');
const destPath = path.join(dataDir, 'cities.js');
const legacyPath = path.join(dataDir, 'cities_legacy.js');

const MIN_YEAR = -10900; // Tell Qaramel — oldest real settlement we want

// Parse the JS file by extracting the array literal
const src = fs.readFileSync(srcPath, 'utf8');
const match = src.match(/window\.CITIES_DATA\s*=\s*(\[[\s\S]*\]);/);
if (!match) { console.error('Could not parse CITIES_DATA'); process.exit(1); }

const cities = JSON.parse(match[1]);
console.log(`Input: ${cities.length} cities`);

const filtered = cities.filter(([, , , , year]) => year === null || year >= MIN_YEAR);
console.log(`After filter (year >= ${MIN_YEAR} or null): ${filtered.length} cities`);
console.log(`Removed: ${cities.length - filtered.length} prehistoric sites`);

// Rename old cities.js -> cities_legacy.js (skip if legacy already exists)
if (fs.existsSync(destPath) && !fs.existsSync(legacyPath)) {
  fs.renameSync(destPath, legacyPath);
  console.log(`Renamed cities.js -> cities_legacy.js`);
}

// Write filtered data as new cities.js
const lines = filtered.map(([name, country, lon, lat, year, imp]) =>
  `  [${JSON.stringify(name)}, ${JSON.stringify(country)}, ${lon.toFixed(3)}, ${lat.toFixed(3)}, ${year ?? 'null'}, ${imp}]`
);
const header = src.match(/^\/\/.+\n\/\/.+\n/)?.[0]
  ?.replace('cities_wikidata.js', 'filter_cities.js')
  ?.replace(/\d+ cities/, `${filtered.length} cities`)
  ?? `// Auto-generated by scripts/filter_cities.js — ${new Date().toISOString().slice(0,10)}\n// ${filtered.length} cities from Wikidata\n`;

fs.writeFileSync(destPath, `${header}window.CITIES_DATA = [\n${lines.join(',\n')}\n];\n`, 'utf8');
console.log(`Written: cities.js`);
